version: '3.7'

services:
  srv:
    build:
      context: .
    ports:
      - "22022:22"
      - "1194:1080"
    environment:
      ROOT_PASS: rwet432mugWRdmiu24876dasbyu6rv674
    restart: always

